
[FX]
	#Avaible, repeat , fast repeat , big explode , none
	boss_death_mode = "fast repeat"
	#Blood in mobs like skeletons or iron golems.
	blood_nflesh = false
	ribs_hurt_half = true
	#Avaible, explosive
	brutal_hurt = "explosive"
	blood_in_screen = true
	#Twenty ticks one second. Modify the time it takes to clean a layer of blood without water, ignore zero number. seconds x twenty.
	blood_in_screen_ticks = 200.0
	max_hurt_particles_amount = 300.0
	max_death_particles_amount = 300.0
	max_brutal_hurt_particles_amount = 300.0
	max_bones_particles_amount = 300.0
	max_death_dust_particles_amount = 300.0

["Particles configuration"]
	xz_area_size = 0.3
	y_area_size = 0.5
	particle_multiplicator = 1.2
	particle_speed_multiplicator = 0.3
	#(Y +)
	center_y_mob = 1.3
	center_y_player = 1.0
	bones_particles_multiplicator = 5.0
	bones_particles_speed_multiplicator = 2.0
	brutal_hurt_particles_multiplicator = 7.0

