const ITEM_LOOT_RARITIES = {
  common: 1,
  uncommon: 2,
  rare: 3,
  veryRare: 4,
  ultraRare: 5,
};

const ITEM_TYPES = {
  food: "FOOD",
  weapon: "WEAPON",
  tool: "TOOL",
  armor: "ARMOR",
  ingredient: "INGREDIENT",
  ore: "ORE",
  ammo: "AMMO",
  medical: "MEDICAL",
  misc: "MISC",
};

const MINECRAFT_ITEMS = [
  {
    id: "minecraft:stick",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "3x minecraft:stick",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 3,
    count: 3,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:paper",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 5,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "3x minecraft:paper",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 5,
    count: 3,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:potato",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "4x minecraft:potato",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 3,
    count: 4,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:string",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 4,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:brick",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:cobweb",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 4,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "minecraft:oak_plants",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 4,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:oak_log",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:clay_ball",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:spruce_log",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:spruce_planks",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:coal",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 5,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:gunpowder",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 4,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "2x minecraft:gunpowder",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 4,
    count: 2,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:iron_ingot",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "minecraft:flint_and_steel",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "minecraft:diamond",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "minecraft",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ingredient,
  },
];

const APOCALYPSE_NOW_ITEMS = [
  {
    id: "apocalypsenow:packofsoup",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "2x apocalypsenow:packofsoup",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 3,
    count: 2,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "3x apocalypsenow:packofsoup",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 3,
    count: 3,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:homemadeantibiotics",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:tomatoscanned",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "4x apocalypsenow:tomatoscanned",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 2,
    count: 4,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:canned_beans",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 5,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "3x apocalypsenow:canned_beans",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 5,
    count: 3,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:can",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:toiletpaper",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:watch",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:glassbottle",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:broken_radio",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:broken_military_radio",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:foodcanned",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "2x apocalypsenow:foodcanned",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 3,
    count: 2,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "4x apocalypsenow:foodcanned",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 3,
    count: 4,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:money",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 5,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "5x apocalypsenow:money",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 5,
    count: 5,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:coins",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 8,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "5x apocalypsenow:coins",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 8,
    count: 5,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "10x apocalypsenow:coins",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 8,
    count: 10,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:radio",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:files",
    nbt: null,
    lootChance: 0.1,
    minAmount: 1,
    maxAmount: 5,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "4x apocalypsenow:files",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 5,
    count: 4,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "7x apocalypsenow:files",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 5,
    count: 7,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:scrapmetal",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:electrical_scrap",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:cellphone",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:comic_book",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "3x apocalypsenow:comic_book",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 2,
    count: 3,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "6x apocalypsenow:comic_book",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 2,
    count: 6,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:strawberrycanned",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 4,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:engineering_parts",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:glue",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:aabattery",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "4x apocalypsenow:aabattery",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 2,
    count: 4,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:alcohol",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:canned_pork",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:bandage",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:pain_killers",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:antibiotics",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:combat_survival_knife",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "apocalypsenow:rou_respirator_helmet",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "apocalypsenow:canned_chili",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:chlorine_dioxed",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "apocalypsenow:electrical_module",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "apocalypsenow:army_boots",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "apocalypsenow:medicalkit",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "apocalypsenow:mre",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "apocalypsenow:soldier_chestplate",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "apocalypsenow:chainsaw",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "apocalypsenow:dynamite",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "apocalypsenow:blackhockeymask_helmet",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "apocalypsenow:soldier_helmet",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "apocalypsenow:biohazard_helmet",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "apocalypsenow:nightvisiongoggles",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "apocalypsenow",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
];

const ZOMBIE_EXTREME_ITEMS = [
  {
    id: "zombie_extreme:police_suit_chestplate",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombie_extreme:night_vision_glasses_helmet",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombie_extreme:juggernaut_suit_leggings",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombie_extreme:last_hope",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "zombie_extreme:steel_pickaxe",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.tool,
  },
  {
    id: "zombie_extreme:batteries",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "zombie_extreme:energy_batteries",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "zombie_extreme:magnetic_card",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "zombie_extreme:black_ops_magnetic_card",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombie_extreme",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
];

const ZOMBIE_ISLAND_ITEMS = [
  {
    id: "zombie_island:scrap",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "zombie_island",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.misc,
  },
  {
    id: "zombie_island:electronics",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "zombie_island",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
];

const CROPTOPIA = [
  {
    id: "croptopia:orange",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "3x croptopia:orange",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 2,
    count: 3,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:mango",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:tomato_juice",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:apple_juice",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:orange_juice",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:cooking_pot",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "croptopia:banana",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:chocolate",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:burrito",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:enchilada",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:tamales",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:blueberry_jam",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:shepherds_pie",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
  {
    id: "croptopia:doughnut",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "croptopia",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.food,
  },
];

const LES_RAISINS_ARMOR_ITEMS = [
  {
    id: "lrarmor:scout_leggings",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:fbi_chestplate",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:fbi_armed_chestplate",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:atf_chestplate",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:dea_boots",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:dea_chestplate",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:chemical_protective_helmet",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:armored_chemical_helmet",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:armored_chemical_chestplate",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:chemical_protective_leggings",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:chemical_protective_boots",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:joker_helmet",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "lrarmor:sniper_helmet",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lrarmor",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
];

const LEGENDARY_SURVIVAL_OVERHAUL = [
  {
    id: "legendarysurvivaloverhaul:bandage",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.medical,
  },
  {
    id: "3x legendarysurvivaloverhaul:bandage",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 2,
    count: 3,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.medical,
  },
  {
    id: "legendarysurvivaloverhaul:canteen",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "legendarysurvivaloverhaul:medikit",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.medical,
  },
  {
    id: "2x legendarysurvivaloverhaul:medikit",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 2,
    count: 2,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.medical,
  },
  {
    id: "legendarysurvivaloverhaul:morphine",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.medical,
  },
  {
    id: "3x legendarysurvivaloverhaul:morphine",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 2,
    count: 3,
    origin: "legendarysurvivaloverhaul",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.medical,
  },
];

const FIRST_AID_ITEMS = [
  {
    id: "firstaid:plaster",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.common,
    type: ITEM_TYPES.medical,
  },
  {
    id: "firstaid:bandage",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.medical,
  },
  {
    id: "firstaid:morphine",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.medical,
  },
];

const MCROWNERS_FLASHLIGHT = [
  {
    id: "mcrowners_flashlight:flashlight",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.tool,
  },
  {
    id: "mcrowners_flashlight:battery",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
];

const MODERN_LIFE_ITEMS = [
  {
    id: "modernlife:battery",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "modernlife:flashlight",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "firstaid",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.tool,
  },
];

const EXTINCTION_ITEMS = [
  {
    id: "extinction:butcher_knife",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "extinction:pipe",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "extinction:riot_shieldii",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.armor,
  },
  {
    id: "extinction:tactical_tomahawk",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "extinction:rusty_axe",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "extinction:axe_1",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "extinction:ff_leggings",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "extinction:a_helmet",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "extinction:backpack",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "extinction:bottle_water",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.uncommon,
    type: ITEM_TYPES.misc,
  },
  {
    id: "extinction:vodka",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "extinction",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
];

const CREATE_ITEMS = [
  {
    id: "create:cogwheel",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 2,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "create:super_glue",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "create:propeller",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "create:metal_bracket",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "create:shaft",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "create:andesite_alloy",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "create:brass_ingot",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "create",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
];

const POWERED_FLASHLIGHT_ITEMS = [
  {
    id: "powered_flashlight:flashlight",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "powered_flashlight",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.misc,
  },
];

const REFINED_STORAGE_ITEMS = [
  {
    id: "refinedstorage:basic_processor",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "refinedstorage",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "refinedstorage:silicon",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "refinedstorage",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
];

const MARBLEDS_ARSENAL_ITEMS = [
  {
    id: "marbledsarsenal:black_plate_carrier_light",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:black_plate_carrier_heavy",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:riot_armor_leggings",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:riot_armor_boots",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:riot_armor_helmet",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:swat_armor_helmet",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:hazmat_armor_helmet",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:hazmat_armor_chestplate",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:hazmat_armor_leggings",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "marbledsarsenal:hazmat_armor_boots",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "marbledsarsenal",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
];

const POINTBLANK_ITEMS = [
  {
    id: "pointblank:doom_combatshotgun",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:doom_handgun",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:m4a1mod1",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:citoricxs",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:wa2000",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:star15",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:rhino",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:m9",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:glock17",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:m32mgl",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "pointblank:ammo9mm",
    nbt: null,
    lootChance: 0.08,
    minAmount: 5,
    maxAmount: 30,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "5x pointblank:ammo9mm",
    nbt: null,
    lootChance: 0.07,
    minAmount: 5,
    maxAmount: 30,
    count: 5,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "10x pointblank:ammo9mm",
    nbt: null,
    lootChance: 0.05,
    minAmount: 5,
    maxAmount: 30,
    count: 10,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:ammo45acp",
    nbt: null,
    lootChance: 0.07,
    minAmount: 4,
    maxAmount: 10,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "10x pointblank:ammo45acp",
    nbt: null,
    lootChance: 0.05,
    minAmount: 4,
    maxAmount: 10,
    count: 10,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "17x pointblank:ammo45acp",
    nbt: null,
    lootChance: 0.03,
    minAmount: 4,
    maxAmount: 10,
    count: 17,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:ammo50ae",
    nbt: null,
    lootChance: 0.06,
    minAmount: 3,
    maxAmount: 10,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "11x pointblank:ammo50ae",
    nbt: null,
    lootChance: 0.05,
    minAmount: 3,
    maxAmount: 10,
    count: 11,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:ammo556",
    nbt: null,
    lootChance: 0.06,
    minAmount: 5,
    maxAmount: 15,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "12x pointblank:ammo556",
    nbt: null,
    lootChance: 0.05,
    minAmount: 5,
    maxAmount: 15,
    count: 12,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "19x pointblank:ammo556",
    nbt: null,
    lootChance: 0.04,
    minAmount: 5,
    maxAmount: 15,
    count: 19,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:ammo12gauge",
    nbt: null,
    lootChance: 0.08,
    minAmount: 5,
    maxAmount: 20,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "10x pointblank:ammo12gauge",
    nbt: null,
    lootChance: 0.07,
    minAmount: 5,
    maxAmount: 20,
    count: 10,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "22x pointblank:ammo12gauge",
    nbt: null,
    lootChance: 0.06,
    minAmount: 5,
    maxAmount: 20,
    count: 22,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:ammo762x51",
    nbt: null,
    lootChance: 0.05,
    minAmount: 5,
    maxAmount: 30,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "10x pointblank:ammo762x51",
    nbt: null,
    lootChance: 0.04,
    minAmount: 5,
    maxAmount: 30,
    count: 10,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "17x pointblank:ammo762x51",
    nbt: null,
    lootChance: 0.03,
    minAmount: 5,
    maxAmount: 30,
    count: 17,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:ammo762",
    nbt: null,
    lootChance: 0.04,
    minAmount: 3,
    maxAmount: 10,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "10x pointblank:ammo762",
    nbt: null,
    lootChance: 0.03,
    minAmount: 3,
    maxAmount: 10,
    count: 10,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "15x pointblank:ammo762",
    nbt: null,
    lootChance: 0.02,
    minAmount: 3,
    maxAmount: 10,
    count: 15,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "pointblank:processor",
    nbt: null,
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "pointblank:gunmetal_ingot",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 3,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "pointblank:gunmetal_ingot",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 3,
    count: 3,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "pointblank:wolf_scope",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:holographic558",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:rspec",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:ar_muzzlebrake",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:shortgrip",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:foregrip",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:ak_supressor",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "pointblank:m203launcher",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "pointblank",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
];

const TACZ_ITEMS = [
  {
    id: "tacz:deagle_golden",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:2000,GunCurrentAmmoCount:9,GunFireMode:"SEMI",GunId:"tacz:deagle_golden",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "tacz:p320",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:2000,GunCurrentAmmoCount:12,GunFireMode:"SEMI",GunId:"tacz:p320",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "immersive_armorer:revolver",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:1996,GunCurrentAmmoCount:8,GunFireMode:"SEMI",GunId:"immersive_armorer:revolver",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "immersive_armorer:assult_rifle",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:1952,GunCurrentAmmoCount:12,GunFireMode:"AUTO",GunId:"immersive_armorer:assult_rifle",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "tacz:db_short",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:1994,GunCurrentAmmoCount:2,GunFireMode:"BURST",GunId:"tacz:db_short",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "tacz:db_long",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:2000,GunCurrentAmmoCount:2,GunFireMode:"SEMI",GunId:"tacz:db_long",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "tacz:ai_awp",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:1999,GunCurrentAmmoCount:4,GunFireMode:"SEMI",GunId:"tacz:ai_awp",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "lradd:nitro_505",
    nbt: Item.of(
      "tacz:modern_kinetic_gun",
      '{Durability:2000,GunCurrentAmmoCount:1,GunFireMode:"SEMI",GunId:"lradd:nitro_505",HasBulletInBarrel:1b}'
    ),
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "tacz:12g",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:12g"}'),
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:12g",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"tacz:12g"}'),
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 10,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:762x54",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:762x54"}'),
    lootChance: 0.07,
    minAmount: 5,
    maxAmount: 10,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:762x54",
    nbt: Item.of("tacz:ammo", 12, '{AmmoId:"tacz:762x54"}'),
    lootChance: 0.06,
    minAmount: 5,
    maxAmount: 10,
    count: 12,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:308",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:308"}'),
    lootChance: 0.04,
    minAmount: 5,
    maxAmount: 15,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:308",
    nbt: Item.of("tacz:ammo", 8, '{AmmoId:"tacz:308"}'),
    lootChance: 0.03,
    minAmount: 5,
    maxAmount: 15,
    count: 8,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:308",
    nbt: Item.of("tacz:ammo", 16, '{AmmoId:"tacz:308"}'),
    lootChance: 0.02,
    minAmount: 5,
    maxAmount: 15,
    count: 16,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:m993",
    nbt: Item.of("tacz:ammo", '{AmmoId:"lradd:m993"}'),
    lootChance: 0.03,
    minAmount: 5,
    maxAmount: 10,
    count: 1,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:m993",
    nbt: Item.of("tacz:ammo", 22, '{AmmoId:"lradd:m993"}'),
    lootChance: 0.02,
    minAmount: 5,
    maxAmount: 10,
    count: 22,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:50ae",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:50ae"}'),
    lootChance: 0.02,
    minAmount: 10,
    maxAmount: 20,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:50ae",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"tacz:50ae"}'),
    lootChance: 0.01,
    minAmount: 10,
    maxAmount: 20,
    count: 10,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "immersive_armorer:ap_ammo",
    nbt: Item.of("tacz:ammo", '{AmmoId:"immersive_armorer:ap_ammo"}'),
    lootChance: 0.05,
    minAmount: 10,
    maxAmount: 30,
    count: 1,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "immersive_armorer:ap_ammo",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"immersive_armorer:ap_ammo"}'),
    lootChance: 0.04,
    minAmount: 10,
    maxAmount: 30,
    count: 10,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "immersive_armorer:ap_ammo",
    nbt: Item.of("tacz:ammo", 18, '{AmmoId:"immersive_armorer:ap_ammo"}'),
    lootChance: 0.03,
    minAmount: 10,
    maxAmount: 30,
    count: 18,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:556x45",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:556x45"}'),
    lootChance: 0.02,
    minAmount: 10,
    maxAmount: 30,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:556x45",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"tacz:556x45"}'),
    lootChance: 0.01,
    minAmount: 10,
    maxAmount: 30,
    count: 10,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:9mm",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:9mm"}'),
    lootChance: 0.08,
    minAmount: 10,
    maxAmount: 20,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:9mm",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"tacz:9mm"}'),
    lootChance: 0.07,
    minAmount: 10,
    maxAmount: 20,
    count: 10,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:9mm",
    nbt: Item.of("tacz:ammo", 25, '{AmmoId:"tacz:9mm"}'),
    lootChance: 0.06,
    minAmount: 10,
    maxAmount: 20,
    count: 25,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:357mag",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:357mag"}'),
    lootChance: 0.06,
    minAmount: 5,
    maxAmount: 10,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:357mag",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"tacz:357mag"}'),
    lootChance: 0.05,
    minAmount: 5,
    maxAmount: 10,
    count: 10,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:357mag",
    nbt: Item.of("tacz:ammo", 17, '{AmmoId:"tacz:357mag"}'),
    lootChance: 0.04,
    minAmount: 5,
    maxAmount: 10,
    count: 17,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:nail",
    nbt: Item.of("tacz:ammo", '{AmmoId:"lradd:nail"}'),
    lootChance: 0.09,
    minAmount: 5,
    maxAmount: 10,
    count: 1,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:nail",
    nbt: Item.of("tacz:ammo", 11, '{AmmoId:"lradd:nail"}'),
    lootChance: 0.08,
    minAmount: 5,
    maxAmount: 10,
    count: 11,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:nail",
    nbt: Item.of("tacz:ammo", 23, '{AmmoId:"lradd:nail"}'),
    lootChance: 0.07,
    minAmount: 5,
    maxAmount: 10,
    count: 23,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "immersive_armorer:burst_capacitor",
    nbt: Item.of("tacz:ammo", '{AmmoId:"immersive_armorer:burst_capacitor"}'),
    lootChance: 0.03,
    minAmount: 5,
    maxAmount: 10,
    count: 1,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:338",
    nbt: Item.of("tacz:ammo", '{AmmoId:"tacz:338"}'),
    lootChance: 0.04,
    minAmount: 5,
    maxAmount: 15,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:338",
    nbt: Item.of("tacz:ammo", 8, '{AmmoId:"tacz:338"}'),
    lootChance: 0.03,
    minAmount: 5,
    maxAmount: 15,
    count: 8,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "tacz:338",
    nbt: Item.of("tacz:ammo", 12, '{AmmoId:"tacz:338"}'),
    lootChance: 0.02,
    minAmount: 5,
    maxAmount: 15,
    count: 12,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:arrow",
    nbt: Item.of("tacz:ammo", '{AmmoId:"lradd:arrow"}'),
    lootChance: 0.07,
    minAmount: 10,
    maxAmount: 20,
    count: 1,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:arrow",
    nbt: Item.of("tacz:ammo", 10, '{AmmoId:"lradd:arrow"}'),
    lootChance: 0.06,
    minAmount: 10,
    maxAmount: 20,
    count: 10,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "lradd:arrow",
    nbt: Item.of("tacz:ammo", 30, '{AmmoId:"lradd:arrow"}'),
    lootChance: 0.05,
    minAmount: 10,
    maxAmount: 20,
    count: 30,
    origin: "lradd",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ammo,
  },
  {
    id: "gundurability:wd_40",
    nbt: null,
    lootChance: 0.09,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "gundurability",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "tacz:stock_tactical_ar",
    nbt: Item.of("tacz:attachment", '{AttachmentId:"tacz:stock_tactical_ar"}'),
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "tacz:stock_militech_b5",
    nbt: Item.of("tacz:attachment", '{AttachmentId:"tacz:stock_militech_b5"}'),
    lootChance: 0.01,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "tacz:grip_vertical_talon",
    nbt: Item.of(
      "tacz:attachment",
      '{AttachmentId:"tacz:grip_vertical_talon"}'
    ),
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "immersive_armorer:grip_twined",
    nbt: Item.of(
      "tacz:attachment",
      '{AttachmentId:"immersive_armorer:grip_twined"}'
    ),
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "tacz:muzzle_silence_phantom_s1",
    nbt: Item.of(
      "tacz:attachment",
      '{AttachmentId:"tacz:muzzle_silence_phantom_s1"}'
    ),
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "immersive_armorer:sight_simple_reflex",
    nbt: Item.of(
      "tacz:attachment",
      '{AttachmentId:"immersive_armorer:sight_simple_reflex"}'
    ),
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "immersive_armorer",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
  {
    id: "tacz:sight_t1",
    nbt: Item.of("tacz:attachment", '{AttachmentId:"tacz:sight_t1"}'),
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "tacz",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.misc,
  },
];

const ZOMBIE_SURVIVAL_KIT_ITEMS = [
  {
    id: "zombiekit:forest_riot_helmet",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:forest_riot_chestplate",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:forest_riot_leggings",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:forest_riot_boots",
    nbt: null,
    lootChance: 0.04,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:snow_tactical_helmet",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:snow_tactical_chestplate",
    nbt: null,
    lootChance: 0.02,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:snow_tactical_leggings",
    nbt: null,
    lootChance: 0.03,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:snow_tactical_boots",
    nbt: null,
    lootChance: 0.05,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.ultraRare,
    type: ITEM_TYPES.armor,
  },
  {
    id: "zombiekit:crowbar",
    nbt: null,
    lootChance: 0.07,
    minAmount: 1,
    maxAmount: 1,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.rare,
    type: ITEM_TYPES.weapon,
  },
  {
    id: "zombiekit:fibre",
    nbt: null,
    lootChance: 0.08,
    minAmount: 1,
    maxAmount: 10,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
  {
    id: "zombiekit:special_steel_sheet",
    nbt: null,
    lootChance: 0.06,
    minAmount: 1,
    maxAmount: 5,
    count: 1,
    origin: "zombiekit",
    rarity: ITEM_LOOT_RARITIES.veryRare,
    type: ITEM_TYPES.ingredient,
  },
];

const ALL_ITEMS = [].concat(
  MINECRAFT_ITEMS,
  APOCALYPSE_NOW_ITEMS,
  CREATE_ITEMS,
  CROPTOPIA,
  EXTINCTION_ITEMS,
  FIRST_AID_ITEMS,
  MODERN_LIFE_ITEMS,
  MCROWNERS_FLASHLIGHT,
  LEGENDARY_SURVIVAL_OVERHAUL,
  LES_RAISINS_ARMOR_ITEMS,
  MARBLEDS_ARSENAL_ITEMS,
  POINTBLANK_ITEMS,
  POWERED_FLASHLIGHT_ITEMS,
  REFINED_STORAGE_ITEMS,
  TACZ_ITEMS,
  ZOMBIE_EXTREME_ITEMS,
  ZOMBIE_ISLAND_ITEMS,
  ZOMBIE_SURVIVAL_KIT_ITEMS
);

const COMMON_ITEMS = [
  Item.of("minecraft:empty").withChance(0.1).withRolls(3, 5),
  Item.of("minecraft:air").withChance(0.1).withRolls(3, 5),
];

const UNCOMMON_ITEMS = [
  Item.of("minecraft:empty").withChance(0.1).withRolls(3, 5),
  Item.of("minecraft:air").withChance(0.1).withRolls(3, 5),
];

const RARE_ITEMS = [
  Item.of("minecraft:empty").withChance(0.1).withRolls(3, 5),
  Item.of("minecraft:air").withChance(0.1).withRolls(3, 5),
];

const VERY_RARE_ITEMS = [
  Item.of("minecraft:empty").withChance(0.1).withRolls(3, 5),
  Item.of("minecraft:air").withChance(0.1).withRolls(3, 5),
];

const ULTRA_RARE_ITEMS = [
  Item.of("minecraft:empty").withChance(0.1).withRolls(3, 5),
  Item.of("minecraft:air").withChance(0.1).withRolls(3, 5),
];

const assignItemToCorrespondingRarityBucket = (
  rarity,
  chance,
  item,
  min,
  max,
  count
) => {
  switch (rarity) {
    case ITEM_LOOT_RARITIES.common:
      COMMON_ITEMS.push(Item.of(item).withChance(chance).withRolls(min, max));
    case ITEM_LOOT_RARITIES.uncommon:
      UNCOMMON_ITEMS.push(Item.of(item).withChance(chance).withRolls(min, max));
    case ITEM_LOOT_RARITIES.rare:
      RARE_ITEMS.push(Item.of(item).withChance(chance).withRolls(min, max));
    case ITEM_LOOT_RARITIES.veryRare:
      VERY_RARE_ITEMS.push(
        Item.of(item).withChance(chance).withRolls(min, max)
      );
    case ITEM_LOOT_RARITIES.ultraRare:
      ULTRA_RARE_ITEMS.push(
        Item.of(item).withChance(chance).withRolls(min, max)
      );
  }
};

ALL_ITEMS.forEach((item) =>
  assignItemToCorrespondingRarityBucket(
    item.rarity,
    item.lootChance,
    item.nbt ? item.nbt : item.id,
    item.minAmount,
    item.maxAmount
  )
);

const RARITY = {
  common: 0.25,
  uncommon: 0.15,
  rare: 0.1,
  ultraRare: 0.05,
  extremelyRare: 0.005,
  insanelyRare: 0.00001,
};

LootJS.modifiers((event) => {
  event
    .addLootTypeModifier(LootType.CHEST)
    .addWeightedLoot([3, 7], COMMON_ITEMS);

  event
    .addLootTypeModifier(LootType.CHEST)
    .addWeightedLoot([2, 4], UNCOMMON_ITEMS);

  event.addLootTypeModifier(LootType.CHEST).addWeightedLoot([0, 2], RARE_ITEMS);

  event
    .addLootTypeModifier(LootType.CHEST)
    .addWeightedLoot([0, 1], VERY_RARE_ITEMS);

  event
    .addLootTypeModifier(LootType.CHEST)
    .addWeightedLoot([0, 1], ULTRA_RARE_ITEMS);

  // loot modifiers for custom block from mods
  event
    .addLootTableModifier("zombie_extreme:cupboard")
    .addWeightedLoot(
      [0, 4],
      [].concat(COMMON_ITEMS, UNCOMMON_ITEMS, RARE_ITEMS)
    );

  event
    .addLootTableModifier("apocalypsenow:large_shelves")
    .addWeightedLoot([0, 4], [].concat(COMMON_ITEMS, UNCOMMON_ITEMS, RARE_ITEMS));

  event
    .addLootTableModifier("apocalypsenow:large_shelves_fill")
    .addWeightedLoot(
      [0, 4],
      [].concat(COMMON_ITEMS, UNCOMMON_ITEMS, RARE_ITEMS)
    );

  event
    .addLootTableModifier("apocalypsenow:large_washing_machine")
    .addWeightedLoot(
      [0, 4],
      [].concat(COMMON_ITEMS, UNCOMMON_ITEMS, RARE_ITEMS)
    );

  // loot modifiers for mod entities
  event
    .addEntityLootModifier(MOBS.zombieIsland.firefighterWalker)
    .addWeightedLoot(
      [1, 2],
      [Item.of("minecraft:blaze_powder").withChance(0.02)]
    );

  event
    .addEntityLootModifier(MOBS.zombieMore.explosiveZombie)
    .addWeightedLoot(
      [1, 3],
      [Item.of("minecraft:blaze_powder").withChance(0.01)]
    );
});
