const MOBS = {
    minecraft: {
        zombie: 'minecraft:zombie',
        creeper: 'minecraft:creeper',
        husk: 'minecraft:husk',
        witch: 'minecraft:witch',
        enderman: 'minecraft:enderman',
        pillager: 'minecraft:pillager',
        vindicator: 'minecraft:vindicator',
        phantom: 'minecraft:phantom',
        spider: 'minecraft:spider',
        skeleton: 'minecraft:skeleton',
        allay: 'minecraft:allay',
        witherSkeleton: 'minecraft:wither_skeleton',
        hoglin: 'minecraft:hoglin'
    },
    apocalypseNow: {
        cannibal: 'apocalypsenow:cannibal',
        runners: {
            runner34: 'apocalypsenow:runner_34',
            runner35: 'apocalypsenow:runner_35',
            runner36: 'apocalypsenow:runner_36',
            runner37: 'apocalypsenow:runner_37',
            runner38: 'apocalypsenow:runner_38',
            runner39: 'apocalypsenow:runner_39',
            runner40: 'apocalypsenow:runner_40',
            runner41: 'apocalypsenow:runner_41',
            runner42: 'apocalypsenow:runner_42',
            runner43: 'apocalypsenow:runner_43',
            runner44: 'apocalypsenow:runner_44',
            runner45: 'apocalypsenow:runner_45',
            runner46: 'apocalypsenow:runner_46',
            runner47: 'apocalypsenow:runner_47',
            runner48: 'apocalypsenow:runner_48',
            runner49: 'apocalypsenow:runner_49',
            runner50: 'apocalypsenow:runner_50',
            runner51: 'apocalypsenow:runner_51',
            runner52: 'apocalypsenow:runner_52',
            runner53: 'apocalypsenow:runner_53',
            runner54: 'apocalypsenow:runner_54',
            runner55: 'apocalypsenow:runner_55',
            runner56: 'apocalypsenow:runner_56',
            runner57: 'apocalypsenow:runner_57'
        },
        hunter: 'apocalypsenow:hunter',
        survivors: {
            survivor1: 'apocalypsenow:survivor_1',
            survivor2: 'apocalypsenow:survivor_2',
            survivor3: 'apocalypsenow:survivor_3',
            survivor4: 'apocalypsenow:survivor_4',
            survivor5: 'apocalypsenow:survivor_5',
            survivor6: 'apocalypsenow:survivor_6',
            survivor7: 'apocalypsenow:survivor_7',
            survivor8: 'apocalypsenow:survivor_8',
            survivor9: 'apocalypsenow:survivor_9',
            survivor10: 'apocalypsenow:survivor_10'
        },
        looters: {
            looter1: 'apocalypsenow:looter_1',
            looter2: 'apocalypsenow:looter_2',
            looter3: 'apocalypsenow:looter_3',
            looter4: 'apocalypsenow:looter_4',
            looter5: 'apocalypsenow:looter_5'
        },
        military1: 'apocalypsenow:military_01',
        military2: 'apocalypsenow:military_02',
        militaryMedic: 'apocalypsenow:military_medic',
        soldiers: 'apocalypsenow:soldiers',
        soldier2: 'apocalypsenow:soldiers_02',
        walkers: {
            walker1: 'apocalypsenow:walker_1',
            walker2: 'apocalypsenow:walker_2',
            walker3: 'apocalypsenow:walker_3',
            walker4: 'apocalypsenow:walker_4',
            walker5: 'apocalypsenow:walker_5',
            walker6: 'apocalypsenow:walker_6',
            walker7: 'apocalypsenow:walker_7',
            walker8: 'apocalypsenow:walker_8',
            walker9: 'apocalypsenow:walker_9',
            walker10: 'apocalypsenow:walker_10',
            walker11: 'apocalypsenow:walker_11',
            walker12: 'apocalypsenow:walker_12',
            walker13: 'apocalypsenow:walker_13',
            walker14: 'apocalypsenow:walker_14',
            walker15: 'apocalypsenow:walker_15',
            walker16: 'apocalypsenow:walker_16',
            walker17: 'apocalypsenow:walker_17',
            walker18: 'apocalypsenow:walker_18',
            walker19: 'apocalypsenow:walker_19',
            walker20: 'apocalypsenow:walker_20',
            walker21: 'apocalypsenow:walker_21',
            walker22: 'apocalypsenow:walker_22',
            walker23: 'apocalypsenow:walker_23',
            walker24: 'apocalypsenow:walker_24',
            walker25: 'apocalypsenow:walker_25',
            walker26: 'apocalypsenow:walker_26',
            walker27: 'apocalypsenow:walker_27',
            walker28: 'apocalypsenow:walker_28',
            walker29: 'apocalypsenow:walker_29',
            walker30: 'apocalypsenow:walker_30',
            walker31: 'apocalypsenow:walker_31',
            walker32: 'apocalypsenow:walker_32',
            walker33: 'apocalypsenow:walker_33'
        },
        hordes: {
            horde1: 'apocalypsenow:horde_1',
            horde2: 'apocalypsenow:horde_2',
            horde3: 'apocalypsenow:horde_3',
            horde4: 'apocalypsenow:horde_4',
            horde5: 'apocalypsenow:horde_5'
        },
        crawlers: {
            crawler1: 'apocalypsenow:crawler_1',
            crawler2: 'apocalypsenow:crawler_2',
            crawler3: 'apocalypsenow:crawler_3',
            crawler4: 'apocalypsenow:crawler_4',
        },
    },
    zombieExtreme: {
        assassinBlackOps: 'zombie_extreme:assasin_black_ops',
        boomer: 'zombie_extreme:boomer',
        chainsaw: 'zombie_extreme:chainsaw',
        clicker: 'zombie_extreme:clicker',
        crawler: 'zombie_extreme:crawler',
        demolisher: 'zombie_extreme:demolisher',
        devestated: 'zombie_extreme:devestated',
        divided: 'zombie_extreme:divided',
        explosiveInfected: 'zombie_extreme:explosive_infected',
        faceless: 'zombie_extreme:faceless',
        fetus: 'zombie_extreme:fetus',
        goon: 'zombie_extreme:goon',
        infected: 'zombie_extreme:infected',
        infectedHazmat: 'zombie_extreme:infected_hazmat',
        infectedJuggernaut: 'zombie_extreme:infected_juggernaut',
        infectedMilitary: 'zombie_extreme:infected_military',
        infectedPolice: 'zombie_extreme:infected_police',
        inflated: 'zombie_extreme:inflated',
        military: 'zombie_extreme:military',
        nightHunter: 'zombie_extreme:night_hunter',
        parasite: 'zombie_extreme:parasite',
        ram: 'zombie_extreme:ram',
        ratKing: 'zombie_extreme:rat_king',
        revived: 'zombie_extreme:revived',
        runner: 'zombie_extreme:runner',
        zeroPatient: 'zombie_extreme:zero_patient'
    },
    zombieIsland: {
        burningWalker: 'zombie_island:burning_walker',
        causticXWalker: 'zombie_island:caustic_x_walker',
        eatCourier: 'zombie_island:eat_courier',
        firefighterWalker: 'zombie_island:firefighter_walker',
        grenadierWalker: 'zombie_island:grenadier_walker',
        hazmatWalker: 'zombie_island:hazmat_walker',
        incendiaryWalker: 'zombie_island:incendiary_walker',
        insectSwarmWalker: 'zombie_island:insect_swarm_walker',
        riotGearWalker: 'zombie_island:riot_gear_walker',
        runner: 'zombie_island:runner',
        runner1: 'zombie_island:runner_1',
        runner2: 'zombie_island:runner_2',
        runner3: 'zombie_island:runner_3',
        runner4: 'zombie_island:runner_4',
        shambler: 'zombie_island:shambler',
        shambler1: 'zombie_island:shambler_1',
        shambler2: 'zombie_island:shambler_2',
        shambler3: 'zombie_island:shambler_3',
        shambler4: 'zombie_island:shambler_4',
        shockingWalker: 'zombie_island:shocking_walker',
        walker: 'zombie_island:walker',
        walker1: 'zombie_island:walker_1',
        walker2: 'zombie_island:walker_2',
        walker3: 'zombie_island:walker_3',
        walker4: 'zombie_island:walker_4'
    },
    zombieMore: {
        boomerZombie: 'zombiesmore:boomer_zombie',
        crawlerZombie: 'zombiesmore:crawler_zombie',
        cursedZombie: 'zombiesmore:cursed_zombie',
        explosiveZombie: 'zombiesmore:explosive_zombie',
        tankZombie: 'zombiesmore:tank_zombie',
    },
    extinction: {
        boomer: 'extinction:boomer',
        fallenSurvivor: 'extinction:fallen_survivor',
        goon: 'extinction:goon',
        hunter: 'extinction:hunter',
        infectedBear: 'extinction:infected_bear',
        infectedHazmat: 'extinction:infected_hazmat',
        infectedMutated: 'extinction:infected_mutated',
        infectedPolice: 'extinction:infected_police',
        infectedRiotGear: 'extinction:infected_riot_gear',
        infectedSoldier: 'extinction:infected_soldier',
        mercenary: 'extinction:mercenary',
        parasite: 'extinction:parasite',
        patientZero: 'extinction:patient_zero',
        runner: 'extinction:runner',
        runner2: 'extinction:runner_ii',
        soldier:  'extinction:soldier',
        soldierClicker: 'extinction:soldier_clicker',
        stalker: 'extinction:stalker',
        stalker2: 'extinction:stalker_ii',
        traveler: 'extinction:traveler'
    },
    taczNpcs: {
        scavUsec: 'tacz_npcs:scav_usec',
        scavUsecArmored: 'tacz_npcs:scav_usec_armored',
        scavUsecPistol: 'tacz_npcs:scav_usec_pistol',
        scavUsecPistolArmored: 'tacz_npcs:scav_usec_pistol_armored',
        terroristNoArmor: 'tacz_npcs:terrorist_no_armor',
        terroristScav: 'tacz_npcs:terrorist_scav',
        terroristScavPistol: 'tacz_npcs:terrorist_scav_pistol',
        terroristScavPistolArmored: 'tacz_npcs:terrorist_scav_pistol_armored'
    },
    mutantMonsters: {
        creeperMinion: 'mutantmonsters:creeper_minion',
        mutantCreeper: 'mutantmonsters:mutant_creeper',
        mutantEnderman: 'mutantmonsters:mutant_enderman',
        mutantSkeleton: 'mutantmonsters:mutant_skeleton',
        mutantSnowGolem: 'mutantmonsters:mutant_snow_golem',
        mutantZombie: 'mutantmonsters:mutant_zombie',
        spiderPig: 'mutantmonsters:spider_pig'
    },
    mekanismAdditions: {
        babyCreeper: 'mekanismadditions:baby_creeper'
    }
};

const SPAWN_WEIGHT = {
    monsters: {
        insanelyRare: '1', // 0.2%
        extremelyRare: '5', // 1.5%
        veryRare: '10',
        rare: '20', // 4.5%
        uncommon: '50', // ~11.25%
        common: '100', // 19%
        veryCommon: '150' // ~30%
    },
    items: {
        
    }
};

const BIOMES = {
    overworld: ['#minecraft:is_overworld'],
    nether: ['#minecraft:is_nether'],
    end: ['#minecraft:is_end']
};